name: Update Packagist

on:
  push:
    branches: [ main, master ]
  delete:
    branches: [ main, master ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packagist update
        run: |
          curl -XPOST -H'Content-Type:application/json' \
          -d '{"repository":{"url":"${{ github.event.repository.html_url }}"}}' \
          'https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}'
